# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(236, 284)
        Form.setMinimumSize(QtCore.QSize(236, 284))
        Form.setMaximumSize(QtCore.QSize(236, 284))
        Form.setFocusPolicy(QtCore.Qt.NoFocus)
        Form.setAcceptDrops(False)
        Form.setStyleSheet("background-color: rgb(146, 135, 125);\n"
"color: rgb(255, 255, 255);\n"
"QPushButton{\n"
"border: 3px;\n"
"background-color: rgb(180, 180, 180)\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.l1_1 = QtWidgets.QLabel(Form)
        self.l1_1.setMinimumSize(QtCore.QSize(50, 50))
        self.l1_1.setMaximumSize(QtCore.QSize(50, 50))
        self.l1_1.setStyleSheet("background-color: rgb(162, 152, 152);")
        self.l1_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l1_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l1_1.setObjectName("l1_1")
        self.gridLayout.addWidget(self.l1_1, 1, 0, 1, 1)
        self.l4_3 = QtWidgets.QLabel(Form)
        self.l4_3.setMinimumSize(QtCore.QSize(50, 50))
        self.l4_3.setMaximumSize(QtCore.QSize(50, 50))
        self.l4_3.setStyleSheet("background-color: rgb(162, 152, 152);")
        self.l4_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l4_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l4_3.setObjectName("l4_3")
        self.gridLayout.addWidget(self.l4_3, 4, 2, 1, 1)
        self.l1_4 = QtWidgets.QLabel(Form)
        self.l1_4.setMinimumSize(QtCore.QSize(50, 50))
        self.l1_4.setMaximumSize(QtCore.QSize(50, 50))
        self.l1_4.setStyleSheet("background-color: rgb(162, 152, 152);")
        self.l1_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l1_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l1_4.setObjectName("l1_4")
        self.gridLayout.addWidget(self.l1_4, 1, 3, 1, 1)
        self.l2_3 = QtWidgets.QLabel(Form)
        self.l2_3.setMinimumSize(QtCore.QSize(50, 50))
        self.l2_3.setMaximumSize(QtCore.QSize(50, 50))
        self.l2_3.setStyleSheet("background-color: rgb(162, 152, 152);")
        self.l2_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l2_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l2_3.setObjectName("l2_3")
        self.gridLayout.addWidget(self.l2_3, 2, 2, 1, 1)
        self.l2_1 = QtWidgets.QLabel(Form)
        self.l2_1.setMinimumSize(QtCore.QSize(50, 50))
        self.l2_1.setMaximumSize(QtCore.QSize(50, 50))
        self.l2_1.setStyleSheet("background-color: rgb(162, 152, 152);")
        self.l2_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l2_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l2_1.setObjectName("l2_1")
        self.gridLayout.addWidget(self.l2_1, 2, 0, 1, 1)
        self.l1_3 = QtWidgets.QLabel(Form)
        self.l1_3.setMinimumSize(QtCore.QSize(50, 50))
        self.l1_3.setMaximumSize(QtCore.QSize(50, 50))
        self.l1_3.setStyleSheet("background-color: rgb(162, 152, 152);")
        self.l1_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l1_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l1_3.setObjectName("l1_3")
        self.gridLayout.addWidget(self.l1_3, 1, 2, 1, 1)
        self.l1_2 = QtWidgets.QLabel(Form)
        self.l1_2.setMinimumSize(QtCore.QSize(50, 50))
        self.l1_2.setMaximumSize(QtCore.QSize(50, 50))
        self.l1_2.setStyleSheet("background-color: rgb(162, 152, 152);")
        self.l1_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l1_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l1_2.setObjectName("l1_2")
        self.gridLayout.addWidget(self.l1_2, 1, 1, 1, 1)
        self.l4_2 = QtWidgets.QLabel(Form)
        self.l4_2.setMinimumSize(QtCore.QSize(50, 50))
        self.l4_2.setMaximumSize(QtCore.QSize(50, 50))
        self.l4_2.setStyleSheet("background-color: rgb(162, 152, 152);")
        self.l4_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l4_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l4_2.setObjectName("l4_2")
        self.gridLayout.addWidget(self.l4_2, 4, 1, 1, 1)
        self.l3_4 = QtWidgets.QLabel(Form)
        self.l3_4.setMinimumSize(QtCore.QSize(50, 50))
        self.l3_4.setMaximumSize(QtCore.QSize(50, 50))
        self.l3_4.setStyleSheet("background-color: rgb(162, 152, 152);")
        self.l3_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l3_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l3_4.setObjectName("l3_4")
        self.gridLayout.addWidget(self.l3_4, 3, 3, 1, 1)
        self.l2_2 = QtWidgets.QLabel(Form)
        self.l2_2.setMinimumSize(QtCore.QSize(50, 50))
        self.l2_2.setMaximumSize(QtCore.QSize(50, 50))
        self.l2_2.setStyleSheet("background-color: rgb(162, 152, 152);")
        self.l2_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l2_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l2_2.setObjectName("l2_2")
        self.gridLayout.addWidget(self.l2_2, 2, 1, 1, 1)
        self.l3_2 = QtWidgets.QLabel(Form)
        self.l3_2.setMinimumSize(QtCore.QSize(50, 50))
        self.l3_2.setMaximumSize(QtCore.QSize(50, 50))
        self.l3_2.setStyleSheet("background-color: rgb(162, 152, 152);")
        self.l3_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l3_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l3_2.setObjectName("l3_2")
        self.gridLayout.addWidget(self.l3_2, 3, 1, 1, 1)
        self.l3_1 = QtWidgets.QLabel(Form)
        self.l3_1.setMinimumSize(QtCore.QSize(50, 50))
        self.l3_1.setMaximumSize(QtCore.QSize(50, 50))
        self.l3_1.setStyleSheet("background-color: rgb(162, 152, 152);")
        self.l3_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l3_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l3_1.setObjectName("l3_1")
        self.gridLayout.addWidget(self.l3_1, 3, 0, 1, 1)
        self.l2_4 = QtWidgets.QLabel(Form)
        self.l2_4.setMinimumSize(QtCore.QSize(50, 50))
        self.l2_4.setMaximumSize(QtCore.QSize(50, 50))
        self.l2_4.setStyleSheet("background-color: rgb(162, 152, 152);")
        self.l2_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l2_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l2_4.setObjectName("l2_4")
        self.gridLayout.addWidget(self.l2_4, 2, 3, 1, 1)
        self.l4_4 = QtWidgets.QLabel(Form)
        self.l4_4.setMinimumSize(QtCore.QSize(50, 50))
        self.l4_4.setMaximumSize(QtCore.QSize(50, 50))
        self.l4_4.setStyleSheet("background-color: rgb(162, 152, 152);")
        self.l4_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l4_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l4_4.setObjectName("l4_4")
        self.gridLayout.addWidget(self.l4_4, 4, 3, 1, 1)
        self.l3_3 = QtWidgets.QLabel(Form)
        self.l3_3.setMinimumSize(QtCore.QSize(50, 50))
        self.l3_3.setMaximumSize(QtCore.QSize(50, 50))
        self.l3_3.setStyleSheet("background-color: rgb(162, 152, 152);")
        self.l3_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l3_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l3_3.setObjectName("l3_3")
        self.gridLayout.addWidget(self.l3_3, 3, 2, 1, 1)
        self.l4_1 = QtWidgets.QLabel(Form)
        self.l4_1.setMinimumSize(QtCore.QSize(50, 50))
        self.l4_1.setMaximumSize(QtCore.QSize(50, 50))
        self.l4_1.setStyleSheet("background-color: rgb(162, 152, 152);")
        self.l4_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l4_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l4_1.setObjectName("l4_1")
        self.gridLayout.addWidget(self.l4_1, 4, 0, 1, 1)
        self.Top_latout = QtWidgets.QHBoxLayout()
        self.Top_latout.setObjectName("Top_latout")
        self.fs = QtWidgets.QLabel(Form)
        self.fs.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.fs.setFont(font)
        self.fs.setObjectName("fs")
        self.Top_latout.addWidget(self.fs)
        self.score_label = QtWidgets.QLabel(Form)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 135, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 135, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 135, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 135, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 135, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 135, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 135, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 135, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 135, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.score_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.score_label.setFont(font)
        self.score_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.score_label.setObjectName("score_label")
        self.Top_latout.addWidget(self.score_label)
        self.replay_button = QtWidgets.QPushButton(Form)
        self.replay_button.setMinimumSize(QtCore.QSize(80, 40))
        self.replay_button.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.replay_button.setFont(font)
        self.replay_button.setMouseTracking(False)
        self.replay_button.setAutoFillBackground(False)
        self.replay_button.setStyleSheet("border: 3px;\n"
"background-color: rgb(180, 180, 180)")
        self.replay_button.setInputMethodHints(QtCore.Qt.ImhNone)
        self.replay_button.setShortcut("")
        self.replay_button.setCheckable(False)
        self.replay_button.setAutoRepeat(False)
        self.replay_button.setAutoExclusive(False)
        self.replay_button.setAutoDefault(False)
        self.replay_button.setDefault(False)
        self.replay_button.setFlat(False)
        self.replay_button.setObjectName("replay_button")
        self.Top_latout.addWidget(self.replay_button)
        self.gridLayout.addLayout(self.Top_latout, 0, 0, 1, 4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "2048"))
        self.l1_1.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"></span></p></body></html>"))
        self.l4_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"></span></p></body></html>"))
        self.l1_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"></span></p></body></html>"))
        self.l2_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"></span></p></body></html>"))
        self.l2_1.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"></span></p></body></html>"))
        self.l1_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"></span></p></body></html>"))
        self.l1_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"></span></p></body></html>"))
        self.l4_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"></span></p></body></html>"))
        self.l3_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"></span></p></body></html>"))
        self.l2_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"></span></p></body></html>"))
        self.l3_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"></span></p></body></html>"))
        self.l3_1.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"></span></p></body></html>"))
        self.l2_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"></span></p></body></html>"))
        self.l4_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"></span></p></body></html>"))
        self.l3_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"></span></p></body></html>"))
        self.l4_1.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"></span></p></body></html>"))
        self.fs.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">分数:</span></p></body></html>"))
        self.score_label.setText(_translate("Form", "<html><head/><body><p>0</p></body></html>"))
        self.replay_button.setText(_translate("Form", "重玩"))

