# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiex.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(236, 180)
        Form.setStyleSheet("background-color: rgb(146, 135, 125);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.l1_6 = QtWidgets.QLabel(Form)
        self.l1_6.setMinimumSize(QtCore.QSize(50, 50))
        self.l1_6.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(False)
        font.setWeight(50)
        self.l1_6.setFont(font)
        self.l1_6.setStyleSheet("background-color: rgb(246, 124, 95);")
        self.l1_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l1_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l1_6.setObjectName("l1_6")
        self.gridLayout.addWidget(self.l1_6, 1, 2, 1, 1)
        self.l1_10 = QtWidgets.QLabel(Form)
        self.l1_10.setMinimumSize(QtCore.QSize(50, 50))
        self.l1_10.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(False)
        font.setWeight(50)
        self.l1_10.setFont(font)
        self.l1_10.setStyleSheet("background-color: rgb(237, 204, 79);")
        self.l1_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l1_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l1_10.setObjectName("l1_10")
        self.gridLayout.addWidget(self.l1_10, 2, 2, 1, 1)
        self.l1_3 = QtWidgets.QLabel(Form)
        self.l1_3.setMinimumSize(QtCore.QSize(50, 50))
        self.l1_3.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(False)
        font.setWeight(50)
        self.l1_3.setFont(font)
        self.l1_3.setStyleSheet("background-color: rgb(237, 224, 200);")
        self.l1_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l1_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l1_3.setObjectName("l1_3")
        self.gridLayout.addWidget(self.l1_3, 0, 3, 1, 1)
        self.l1_7 = QtWidgets.QLabel(Form)
        self.l1_7.setMinimumSize(QtCore.QSize(50, 50))
        self.l1_7.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(False)
        font.setWeight(50)
        self.l1_7.setFont(font)
        self.l1_7.setStyleSheet("background-color: rgb(246, 94, 59);")
        self.l1_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l1_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l1_7.setObjectName("l1_7")
        self.gridLayout.addWidget(self.l1_7, 1, 3, 1, 1)
        self.l1_8 = QtWidgets.QLabel(Form)
        self.l1_8.setMinimumSize(QtCore.QSize(50, 50))
        self.l1_8.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(False)
        font.setWeight(50)
        self.l1_8.setFont(font)
        self.l1_8.setStyleSheet("background-color: rgb(237, 207, 114);")
        self.l1_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l1_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l1_8.setObjectName("l1_8")
        self.gridLayout.addWidget(self.l1_8, 1, 4, 1, 1)
        self.l1_4 = QtWidgets.QLabel(Form)
        self.l1_4.setMinimumSize(QtCore.QSize(50, 50))
        self.l1_4.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(False)
        font.setWeight(50)
        self.l1_4.setFont(font)
        self.l1_4.setStyleSheet("background-color: rgb(242, 177, 121);")
        self.l1_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l1_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l1_4.setObjectName("l1_4")
        self.gridLayout.addWidget(self.l1_4, 0, 4, 1, 1)
        self.l1_2 = QtWidgets.QLabel(Form)
        self.l1_2.setMinimumSize(QtCore.QSize(50, 50))
        self.l1_2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(False)
        font.setWeight(50)
        self.l1_2.setFont(font)
        self.l1_2.setStyleSheet("background-color: rgb(238, 228, 218);")
        self.l1_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l1_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l1_2.setObjectName("l1_2")
        self.gridLayout.addWidget(self.l1_2, 0, 2, 1, 1)
        self.l1_11 = QtWidgets.QLabel(Form)
        self.l1_11.setMinimumSize(QtCore.QSize(50, 50))
        self.l1_11.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(False)
        font.setWeight(50)
        self.l1_11.setFont(font)
        self.l1_11.setStyleSheet("background-color: rgb(237, 204, 61);")
        self.l1_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l1_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l1_11.setObjectName("l1_11")
        self.gridLayout.addWidget(self.l1_11, 2, 3, 1, 1)
        self.l1_12 = QtWidgets.QLabel(Form)
        self.l1_12.setMinimumSize(QtCore.QSize(50, 50))
        self.l1_12.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(False)
        font.setWeight(50)
        self.l1_12.setFont(font)
        self.l1_12.setStyleSheet("background-color: rgb(237, 204, 43);")
        self.l1_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l1_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l1_12.setObjectName("l1_12")
        self.gridLayout.addWidget(self.l1_12, 2, 4, 1, 1)
        self.l1_1 = QtWidgets.QLabel(Form)
        self.l1_1.setMinimumSize(QtCore.QSize(50, 50))
        self.l1_1.setMaximumSize(QtCore.QSize(50, 50))
        self.l1_1.setStyleSheet("background-color: rgb(162, 152, 152);")
        self.l1_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l1_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l1_1.setObjectName("l1_1")
        self.gridLayout.addWidget(self.l1_1, 0, 1, 1, 1)
        self.l1_5 = QtWidgets.QLabel(Form)
        self.l1_5.setMinimumSize(QtCore.QSize(50, 50))
        self.l1_5.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(False)
        font.setWeight(50)
        self.l1_5.setFont(font)
        self.l1_5.setStyleSheet("background-color: rgb(245, 149, 99);")
        self.l1_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l1_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l1_5.setObjectName("l1_5")
        self.gridLayout.addWidget(self.l1_5, 1, 1, 1, 1)
        self.l1_9 = QtWidgets.QLabel(Form)
        self.l1_9.setMinimumSize(QtCore.QSize(50, 50))
        self.l1_9.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(False)
        font.setWeight(50)
        self.l1_9.setFont(font)
        self.l1_9.setStyleSheet("background-color: rgb(237, 204, 97);")
        self.l1_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l1_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l1_9.setObjectName("l1_9")
        self.gridLayout.addWidget(self.l1_9, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.l1_6.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#f9f6f2;\">32</span></p></body></html>"))
        self.l1_10.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#f9f6f2;\">512</span></p></body></html>"))
        self.l1_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#46413b;\">4</span></p></body></html>"))
        self.l1_7.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#f9f6f2;\">64</span></p></body></html>"))
        self.l1_8.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#f9f6f2;\">128</span></p></body></html>"))
        self.l1_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#f9f6f2;\">8</span></p></body></html>"))
        self.l1_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#46413b;\">2</span></p></body></html>"))
        self.l1_11.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#f9f6f2;\">1024</span></p></body></html>"))
        self.l1_12.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#f9f6f2;\">2048</span></p></body></html>"))
        self.l1_1.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"></span></p></body></html>"))
        self.l1_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#f9f6f2;\">16</span></p></body></html>"))
        self.l1_9.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#f9f6f2;\">256</span></p></body></html>"))

